spring:
  cloud:
    gateway:
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path = /cars/**

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path = /reservations/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path = /users/**

