spring:
  cloud:
    gateway:
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path = car-service/cars/**
          filters:
            - StripPrefix = 1

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path = reservation-service/reservations/**
          filters:
            - StripPrefix = 1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path = user-service/users/**
          filters:
            - StripPrefix = 1

