spring:
  cloud:
    gateway:
      routes:
        - id: car-service
          uri: lb://CAR-SERVICE # Use the registered service name
          predicates:
            - Path=/cars/**
          filters:
            - StripPrefix=1

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE # Use the registered service name
          predicates:
            - Path=/reservations/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-SERVICE # Use the registered service name
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
